// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: battle_service/main.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { GameConfig } from "../types";

export const protobufPackage = "battle_service";

export interface GetActiveBattlesRequest {
  /** id игрока */
  uid: number;
}

export interface GetActiveBattlesResponse {
  /** массив игр (укороченная версия настроек, полные настройки можно загрузить отдельно) */
  battles: GameConfig[];
}

function createBaseGetActiveBattlesRequest(): GetActiveBattlesRequest {
  return { uid: 0 };
}

export const GetActiveBattlesRequest: MessageFns<GetActiveBattlesRequest> = {
  encode(message: GetActiveBattlesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== 0) {
      writer.uint32(8).int32(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActiveBattlesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActiveBattlesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.uid = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActiveBattlesRequest {
    return { uid: isSet(object.uid) ? globalThis.Number(object.uid) : 0 };
  },

  toJSON(message: GetActiveBattlesRequest): unknown {
    const obj: any = {};
    if (message.uid !== 0) {
      obj.uid = Math.round(message.uid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActiveBattlesRequest>, I>>(base?: I): GetActiveBattlesRequest {
    return GetActiveBattlesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActiveBattlesRequest>, I>>(object: I): GetActiveBattlesRequest {
    const message = createBaseGetActiveBattlesRequest();
    message.uid = object.uid ?? 0;
    return message;
  },
};

function createBaseGetActiveBattlesResponse(): GetActiveBattlesResponse {
  return { battles: [] };
}

export const GetActiveBattlesResponse: MessageFns<GetActiveBattlesResponse> = {
  encode(message: GetActiveBattlesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.battles) {
      GameConfig.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetActiveBattlesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetActiveBattlesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.battles.push(GameConfig.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetActiveBattlesResponse {
    return {
      battles: globalThis.Array.isArray(object?.battles) ? object.battles.map((e: any) => GameConfig.fromJSON(e)) : [],
    };
  },

  toJSON(message: GetActiveBattlesResponse): unknown {
    const obj: any = {};
    if (message.battles?.length) {
      obj.battles = message.battles.map((e) => GameConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetActiveBattlesResponse>, I>>(base?: I): GetActiveBattlesResponse {
    return GetActiveBattlesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetActiveBattlesResponse>, I>>(object: I): GetActiveBattlesResponse {
    const message = createBaseGetActiveBattlesResponse();
    message.battles = object.battles?.map((e) => GameConfig.fromPartial(e)) || [];
    return message;
  },
};

export type GoMatchMakingService = typeof GoMatchMakingService;
export const GoMatchMakingService = {
  getActiveBattles: {
    path: "/battle_service.GoMatchMaking/GetActiveBattles",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetActiveBattlesRequest): Buffer =>
      Buffer.from(GetActiveBattlesRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetActiveBattlesRequest => GetActiveBattlesRequest.decode(value),
    responseSerialize: (value: GetActiveBattlesResponse): Buffer =>
      Buffer.from(GetActiveBattlesResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetActiveBattlesResponse => GetActiveBattlesResponse.decode(value),
  },
} as const;

export interface GoMatchMakingServer extends UntypedServiceImplementation {
  getActiveBattles: handleUnaryCall<GetActiveBattlesRequest, GetActiveBattlesResponse>;
}

export interface GoMatchMakingClient extends Client {
  getActiveBattles(
    request: GetActiveBattlesRequest,
    callback: (error: ServiceError | null, response: GetActiveBattlesResponse) => void,
  ): ClientUnaryCall;
  getActiveBattles(
    request: GetActiveBattlesRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetActiveBattlesResponse) => void,
  ): ClientUnaryCall;
  getActiveBattles(
    request: GetActiveBattlesRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetActiveBattlesResponse) => void,
  ): ClientUnaryCall;
}

export const GoMatchMakingClient = makeGenericClientConstructor(
  GoMatchMakingService,
  "battle_service.GoMatchMaking",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): GoMatchMakingClient;
  service: typeof GoMatchMakingService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
