version: '3'

vars:
  PROTO_DIR: proto
  OUT_GO_DIR: gen/go

  USER_SERVICE: user_service

tasks:
  gen-user-service:
    desc: "Генерирует golang файлы для user-service"
    vars:
      FILE: main.proto
    cmds:
      - powershell -Command "New-Item -ItemType Directory -Force -Path '{{.OUT_GO_DIR}}/{{.USER_SERVICE_DIR}}'"
      - powershell -Command "protoc -I {{.PROTO_DIR}} {{.PROTO_DIR}}/{{.USER_SERVICE}}/{{.FILE}} --go_out={{.OUT_GO_DIR}}/{{.USER_SERVICE_DIR}} --go_opt=paths=source_relative --go-grpc_out={{.OUT_GO_DIR}}/{{.USER_SERVICE_DIR}} --go-grpc_opt=paths=source_relative" {{.USER_SERVICE_DIR}}
    platforms: [windows]