// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.5
//   protoc               v6.31.1
// source: match_making/main.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientUnaryCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";
import { GameConfig } from "../types";

export const protobufPackage = "match_making";

export interface GetRequestRequest {
  /** id юзера для которого запрашиваются запросы */
  uid: number;
}

export interface GetRequestResponse {
  /** массив игр */
  requests: GameConfig[];
}

export interface RequestRequest {
  /** id отправителя запроса */
  from: number;
  /** id получателя запроса */
  to: number;
  /** id игры */
  id: number;
  game: GameConfig | undefined;
}

export interface RequestResponse {
  /** id игры */
  id: number;
}

export interface MoveRequest {
  name: string;
  email: string;
  password: string;
}

export interface MoveResponse {
  id: string;
  name: string;
  email: string;
}

function createBaseGetRequestRequest(): GetRequestRequest {
  return { uid: 0 };
}

export const GetRequestRequest: MessageFns<GetRequestRequest> = {
  encode(message: GetRequestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.uid !== 0) {
      writer.uint32(8).int32(message.uid);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRequestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRequestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.uid = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRequestRequest {
    return { uid: isSet(object.uid) ? globalThis.Number(object.uid) : 0 };
  },

  toJSON(message: GetRequestRequest): unknown {
    const obj: any = {};
    if (message.uid !== 0) {
      obj.uid = Math.round(message.uid);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRequestRequest>, I>>(base?: I): GetRequestRequest {
    return GetRequestRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRequestRequest>, I>>(object: I): GetRequestRequest {
    const message = createBaseGetRequestRequest();
    message.uid = object.uid ?? 0;
    return message;
  },
};

function createBaseGetRequestResponse(): GetRequestResponse {
  return { requests: [] };
}

export const GetRequestResponse: MessageFns<GetRequestResponse> = {
  encode(message: GetRequestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.requests) {
      GameConfig.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetRequestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetRequestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.requests.push(GameConfig.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetRequestResponse {
    return {
      requests: globalThis.Array.isArray(object?.requests)
        ? object.requests.map((e: any) => GameConfig.fromJSON(e))
        : [],
    };
  },

  toJSON(message: GetRequestResponse): unknown {
    const obj: any = {};
    if (message.requests?.length) {
      obj.requests = message.requests.map((e) => GameConfig.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetRequestResponse>, I>>(base?: I): GetRequestResponse {
    return GetRequestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetRequestResponse>, I>>(object: I): GetRequestResponse {
    const message = createBaseGetRequestResponse();
    message.requests = object.requests?.map((e) => GameConfig.fromPartial(e)) || [];
    return message;
  },
};

function createBaseRequestRequest(): RequestRequest {
  return { from: 0, to: 0, id: 0, game: undefined };
}

export const RequestRequest: MessageFns<RequestRequest> = {
  encode(message: RequestRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.from !== 0) {
      writer.uint32(8).int32(message.from);
    }
    if (message.to !== 0) {
      writer.uint32(16).int32(message.to);
    }
    if (message.id !== 0) {
      writer.uint32(24).int32(message.id);
    }
    if (message.game !== undefined) {
      GameConfig.encode(message.game, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.from = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.to = reader.int32();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.game = GameConfig.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestRequest {
    return {
      from: isSet(object.from) ? globalThis.Number(object.from) : 0,
      to: isSet(object.to) ? globalThis.Number(object.to) : 0,
      id: isSet(object.id) ? globalThis.Number(object.id) : 0,
      game: isSet(object.game) ? GameConfig.fromJSON(object.game) : undefined,
    };
  },

  toJSON(message: RequestRequest): unknown {
    const obj: any = {};
    if (message.from !== 0) {
      obj.from = Math.round(message.from);
    }
    if (message.to !== 0) {
      obj.to = Math.round(message.to);
    }
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    if (message.game !== undefined) {
      obj.game = GameConfig.toJSON(message.game);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestRequest>, I>>(base?: I): RequestRequest {
    return RequestRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestRequest>, I>>(object: I): RequestRequest {
    const message = createBaseRequestRequest();
    message.from = object.from ?? 0;
    message.to = object.to ?? 0;
    message.id = object.id ?? 0;
    message.game = (object.game !== undefined && object.game !== null)
      ? GameConfig.fromPartial(object.game)
      : undefined;
    return message;
  },
};

function createBaseRequestResponse(): RequestResponse {
  return { id: 0 };
}

export const RequestResponse: MessageFns<RequestResponse> = {
  encode(message: RequestResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== 0) {
      writer.uint32(8).int32(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RequestResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRequestResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.id = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RequestResponse {
    return { id: isSet(object.id) ? globalThis.Number(object.id) : 0 };
  },

  toJSON(message: RequestResponse): unknown {
    const obj: any = {};
    if (message.id !== 0) {
      obj.id = Math.round(message.id);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RequestResponse>, I>>(base?: I): RequestResponse {
    return RequestResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RequestResponse>, I>>(object: I): RequestResponse {
    const message = createBaseRequestResponse();
    message.id = object.id ?? 0;
    return message;
  },
};

function createBaseMoveRequest(): MoveRequest {
  return { name: "", email: "", password: "" };
}

export const MoveRequest: MessageFns<MoveRequest> = {
  encode(message: MoveRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(18).string(message.email);
    }
    if (message.password !== "") {
      writer.uint32(26).string(message.password);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MoveRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoveRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.email = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.password = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MoveRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
      password: isSet(object.password) ? globalThis.String(object.password) : "",
    };
  },

  toJSON(message: MoveRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    if (message.password !== "") {
      obj.password = message.password;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MoveRequest>, I>>(base?: I): MoveRequest {
    return MoveRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MoveRequest>, I>>(object: I): MoveRequest {
    const message = createBaseMoveRequest();
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    message.password = object.password ?? "";
    return message;
  },
};

function createBaseMoveResponse(): MoveResponse {
  return { id: "", name: "", email: "" };
}

export const MoveResponse: MessageFns<MoveResponse> = {
  encode(message: MoveResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): MoveResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseMoveResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): MoveResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: MoveResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<MoveResponse>, I>>(base?: I): MoveResponse {
    return MoveResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<MoveResponse>, I>>(object: I): MoveResponse {
    const message = createBaseMoveResponse();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

export type GoMatchMakingService = typeof GoMatchMakingService;
export const GoMatchMakingService = {
  getRequest: {
    path: "/match_making.GoMatchMaking/GetRequest",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetRequestRequest): Buffer => Buffer.from(GetRequestRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): GetRequestRequest => GetRequestRequest.decode(value),
    responseSerialize: (value: GetRequestResponse): Buffer => Buffer.from(GetRequestResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): GetRequestResponse => GetRequestResponse.decode(value),
  },
  request: {
    path: "/match_making.GoMatchMaking/Request",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: RequestRequest): Buffer => Buffer.from(RequestRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): RequestRequest => RequestRequest.decode(value),
    responseSerialize: (value: RequestResponse): Buffer => Buffer.from(RequestResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): RequestResponse => RequestResponse.decode(value),
  },
  cancelRequest: {
    path: "/match_making.GoMatchMaking/CancelRequest",
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: MoveRequest): Buffer => Buffer.from(MoveRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): MoveRequest => MoveRequest.decode(value),
    responseSerialize: (value: MoveResponse): Buffer => Buffer.from(MoveResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): MoveResponse => MoveResponse.decode(value),
  },
} as const;

export interface GoMatchMakingServer extends UntypedServiceImplementation {
  getRequest: handleUnaryCall<GetRequestRequest, GetRequestResponse>;
  request: handleUnaryCall<RequestRequest, RequestResponse>;
  cancelRequest: handleUnaryCall<MoveRequest, MoveResponse>;
}

export interface GoMatchMakingClient extends Client {
  getRequest(
    request: GetRequestRequest,
    callback: (error: ServiceError | null, response: GetRequestResponse) => void,
  ): ClientUnaryCall;
  getRequest(
    request: GetRequestRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: GetRequestResponse) => void,
  ): ClientUnaryCall;
  getRequest(
    request: GetRequestRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: GetRequestResponse) => void,
  ): ClientUnaryCall;
  request(
    request: RequestRequest,
    callback: (error: ServiceError | null, response: RequestResponse) => void,
  ): ClientUnaryCall;
  request(
    request: RequestRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: RequestResponse) => void,
  ): ClientUnaryCall;
  request(
    request: RequestRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: RequestResponse) => void,
  ): ClientUnaryCall;
  cancelRequest(
    request: MoveRequest,
    callback: (error: ServiceError | null, response: MoveResponse) => void,
  ): ClientUnaryCall;
  cancelRequest(
    request: MoveRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: MoveResponse) => void,
  ): ClientUnaryCall;
  cancelRequest(
    request: MoveRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: MoveResponse) => void,
  ): ClientUnaryCall;
}

export const GoMatchMakingClient = makeGenericClientConstructor(
  GoMatchMakingService,
  "match_making.GoMatchMaking",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): GoMatchMakingClient;
  service: typeof GoMatchMakingService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
